# Generated by Django 4.1.4 on 2023-05-08 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_profile_description_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='clicked',
        ),
    ]
