# Generated by Django 4.1.4 on 2023-05-12 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_likes_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=2000, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
