# Generated by Django 4.1.4 on 2023-05-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_post_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
